disabled = false
locale = "en"
label = "English"
weight = 1
title = "Reed Wilson"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Personal website and blog for Reed Wilson."
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Reed Wilson"
  links = [
    { github = "https://github.com/reedcwilson" },
    { linkedin = "https://www.linkedin.com/in/reedcwilson" },
  ]
